import React from 'react';
import Link from 'next/link';
import { Shield, FileText, AlertCircle, RefreshCw, Scale } from 'lucide-react';
import { ROBINHOOD_USDG_CONTRACT } from '@/lib/payments/x402Facilitator';

export const metadata = {
  title: 'Terms of Service — Waggle',
  description: 'Terms of service, x402 payment rules, refund policy, and research disclaimer for Waggle.'
};

export default function TermsPage() {
  return (
    <div className="wrap">
      <section className="hero">
        <div className="eyebrow">compliance & disclosures</div>
        <h1>Terms of Service</h1>
        <p className="lede">
          Please read these terms carefully before accessing Waggle, utilizing the Scout quantitative engine, or authorizing gasless x402 payments.
        </p>
      </section>

      <section style={{ maxWidth: 860, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 28 }}>
        {/* Section 1: Non-Financial Advice */}
        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
            <Scale size={20} style={{ color: '#2563eb' }} />
            <h2 style={{ margin: 0, fontSize: '1.15rem' }}>1. Research Reports & Non-Financial Advice</h2>
          </div>
          <p style={{ margin: 0, color: 'var(--dim)', lineHeight: 1.6, fontSize: '0.9rem' }}>
            All metrics, structural scores, venue recommendations, and dimension breakdowns generated by Waggle are based strictly on <b>historical, empirical onchain data</b>. They represent quantitative taxonomy and liquidity survival observations, <b>not financial, investment, legal, or trading advice</b>.
          </p>
          <div style={{ marginTop: 12, padding: 12, background: 'rgba(37, 99, 235, 0.06)', borderRadius: 8, border: '1px solid rgba(37, 99, 235, 0.15)', fontSize: '0.82rem', color: '#1d4ed8' }}>
            No score, classification, or suggested launch window constitutes a guarantee or prediction of token performance, market capitalization, or survivability. You assume full responsibility for your deployment decisions.
          </div>
        </div>

        {/* Section 2: Gasless x402 Payments */}
        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
            <Shield size={20} style={{ color: '#059669' }} />
            <h2 style={{ margin: 0, fontSize: '1.15rem' }}>2. Gasless x402 Payment Settlement (EIP-3009)</h2>
          </div>
          <p style={{ margin: 0, color: 'var(--dim)', lineHeight: 1.6, fontSize: '0.9rem' }}>
            Waggle supports paid detailed analysis reports via the <b>x402 protocol</b> using EIP-3009 (<code>transferWithAuthorization</code>) in USDG on Robinhood Chain (Contract: <code>{ROBINHOOD_USDG_CONTRACT}</code>) and Base USDC:
          </p>
          <ul style={{ margin: '12px 0 0', paddingLeft: 20, color: 'var(--dim)', fontSize: '0.88rem', lineHeight: 1.6 }}>
            <li><b>Gasless Execution:</b> Users sign an offchain authorization message; the facilitator covers all network gas fees for onchain settlement.</li>
            <li><b>Zero-Leakage Invariant:</b> Analysis reports are generated and held server-side, released <i>only</i> after onchain settlement confirmation. If an onchain transaction reverts, no payment is captured and the report is withheld.</li>
            <li><b>Deterministic Nonce:</b> Nonces are cryptographically bound to <code>keccak256(abi.encode(from, idempotencyKey))</code>, preventing unauthorized transaction replay.</li>
          </ul>
        </div>

        {/* Section 3: Refund & Retry Policy */}
        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
            <RefreshCw size={20} style={{ color: '#d97706' }} />
            <h2 style={{ margin: 0, fontSize: '1.15rem' }}>3. Refund, Retry & Cancellation Policy</h2>
          </div>
          <p style={{ margin: 0, color: 'var(--dim)', lineHeight: 1.6, fontSize: '0.9rem' }}>
            Because our payment flow enforces atomic settlement prior to report delivery:
          </p>
          <ul style={{ margin: '12px 0 0', paddingLeft: 20, color: 'var(--dim)', fontSize: '0.88rem', lineHeight: 1.6 }}>
            <li><b>Failed Transactions:</b> If an onchain settlement fails or is aborted by the client via <code>cancelAuthorization</code>, your tokens remain in your wallet. No charges occur.</li>
            <li><b>Automatic Retry:</b> In the event of network congestion or temporary RPC timeouts, the transaction state machine retains idempotency locks for 5 minutes. You may resubmit the identical idempotency key to complete delivery without double-charging.</li>
            <li><b>Disputed Settlements:</b> If an onchain transfer was mined but server crash prevented immediate delivery, our <b>Startup Crash Recovery Job</b> automatically resolves the transaction and delivers the cached encrypted report upon recovery.</li>
          </ul>
        </div>

        {/* Section 4: Conflict of Interest */}
        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
            <AlertCircle size={20} style={{ color: '#7c3aed' }} />
            <h2 style={{ margin: 0, fontSize: '1.15rem' }}>4. Conflict of Interest & Operator Disclosures</h2>
          </div>
          <p style={{ margin: 0, color: 'var(--dim)', lineHeight: 1.6, fontSize: '0.9rem' }}>
            Waggle is operated by Modus Research Lab. We adhere to strict neutrality rules:
          </p>
          <ul style={{ margin: '12px 0 0', paddingLeft: 20, color: 'var(--dim)', fontSize: '0.88rem', lineHeight: 1.6 }}>
            <li>We <b>never accept payment</b> from launchpads, DEXs, or blockchains for placement, ranking boosts, or score adjustments.</li>
            <li>We <b>never take equity or token allocations</b> in scored launchpads.</li>
            <li><b>Factual Historical Disclosure:</b> Modus Research Lab previously deployed an experimental token on Pons. This fact does not alter Pons's scoring weights or empirical survival data.</li>
          </ul>
        </div>
      </section>

      <footer style={{ marginTop: 60, textAlign: 'center', fontSize: '0.8rem', color: 'var(--dim)' }}>
        <p>Last updated: September 2026 · Waggle Protocol v2</p>
        <p>
          <Link href="/privacy" style={{ color: '#2563eb', marginRight: 14 }}>Privacy Policy</Link>
          <Link href="/method" style={{ color: '#2563eb', marginRight: 14 }}>Methodology</Link>
          <Link href="/verify" style={{ color: '#2563eb' }}>Verify Onchain</Link>
        </p>
      </footer>
    </div>
  );
}
